#include "../inc/header.h"

void mx_load_textures(t_game_textures *textures) {
    textures->settings = LoadTexture("resource/images/settings.png");
    textures->volume_on = LoadTexture("resource/images/volume1.png");
    textures->volume_on2 = LoadTexture("resource/images/volume3.png");
    textures->music_on = LoadTexture("resource/images/music1.png");
    textures->arrow = LoadTexture("resource/images/arrow_back.png");
    textures->volume_off = LoadTexture("resource/images/volume2.png");
    textures->music_off = LoadTexture("resource/images/music2.png");
    textures->del_texture = LoadTexture("resource/images/delete.png");
    textures->guide = LoadTexture("resource/images/guide.png");
    textures->exit = LoadTexture("resource/images/exit.png");
    textures->pause = LoadTexture("resource/images/pause.png");
    textures->background = LoadTexture("resource/images/menu_background.png");
    textures->play_button = LoadTexture("resource/images/play_button.png");
    textures->star = LoadTexture("resource/images/star.png");
    textures->one_player = LoadTexture("resource/images/one_player.png");
    textures->two_players = LoadTexture("resource/images/two_players.png");
    textures->chef = LoadTexture("resource/images/chef.png");
    textures->right_arrow = LoadTexture("resource/images/arrow_right.png");
    textures->map3 = LoadTexture("resource/images/map.png");
    textures->image3 = LoadTexture("resource/images/image.png");
    textures->level_preview = LoadTexture("resource/images/level_preview.png");
    textures->left_arrow = LoadTexture("resource/images/arrow_left.png");
    textures->served_icon = LoadTexture("resource/images/served_icon.png");
    textures->guest = LoadTexture("resource/images/bee.png");
    textures->reversed_guest = LoadTexture("resource/images/reversedBee.png");
    textures->dirty_apple = LoadTexture("resource/images/dirtyApple.png");
    textures->washed_apple = LoadTexture("resource/images/washedApple.png");
    textures->sliced_apple = LoadTexture("resource/images/slicedApple.png");
    textures->juice = LoadTexture("resource/images/juice.png");
    textures->dirty_potato = LoadTexture("resource/images/dirtyPotato.png");
    textures->washed_potato = LoadTexture("resource/images/washedPotato.png");
    textures->peeled_potato = LoadTexture("resource/images/peeledPotato.png");
    textures->sliced_potato = LoadTexture("resource/images/slicedPotato.png");
    textures->fried_potato = LoadTexture("resource/images/friedPotato.png");
    textures->dirty_cucumber = LoadTexture("resource/images/dirtyCucumber.png");
    textures->washed_cucumber = LoadTexture("resource/images/washedCucumber.png");
    textures->sliced_cucumber = LoadTexture("resource/images/slicedCucumber.png");
    textures->dirty_tomato = LoadTexture("resource/images/dirtyTomato.png");
    textures->washed_tomato = LoadTexture("resource/images/washedTomato.png");
    textures->sliced_tomato = LoadTexture("resource/images/slicedTomato.png");
    textures->salad = LoadTexture("resource/images/salad.png");
    textures->guide_juice = LoadTexture("resource/images/guidePage1.png");
    textures->guide_potato = LoadTexture("resource/images/guidePage2.png");
    textures->guide_salad = LoadTexture("resource/images/guidePage3.png");
    textures->image1 = LoadTexture("resource/images/image_lvl_1.png");
    textures->image2 = LoadTexture("resource/images/image_lvl_2.png");
    textures->map1 = LoadTexture("resource/images/map1.png");
    textures->map2 = LoadTexture("resource/images/map2.png");
    textures->cloud = LoadTexture("resource/images/cloud.png");
    textures->f_button = LoadTexture("resource/images/fButton.png");
}

void mx_unload_textures(t_game_textures *textures) {
    UnloadTexture(textures->settings);
    UnloadTexture(textures->volume_on);
    UnloadTexture(textures->volume_on2);
    UnloadTexture(textures->music_on);
    UnloadTexture(textures->volume_off);
    UnloadTexture(textures->music_off);
    UnloadTexture(textures->arrow);
    UnloadTexture(textures->guide);
    UnloadTexture(textures->del_texture);
    UnloadTexture(textures->background);
    UnloadTexture(textures->play_button);
    UnloadTexture(textures->star);
    UnloadTexture(textures->exit);
    UnloadTexture(textures->pause);
    UnloadTexture(textures->one_player);
    UnloadTexture(textures->two_players);
    UnloadTexture(textures->chef);
    UnloadTexture(textures->right_arrow);
    UnloadTexture(textures->map3);
    UnloadTexture(textures->image3);
    UnloadTexture(textures->level_preview);
    UnloadTexture(textures->left_arrow);
    UnloadTexture(textures->served_icon);
    UnloadTexture(textures->guest);
    UnloadTexture(textures->reversed_guest);
    UnloadTexture(textures->dirty_apple);
    UnloadTexture(textures->washed_apple);
    UnloadTexture(textures->sliced_apple);
    UnloadTexture(textures->juice);
    UnloadTexture(textures->dirty_potato);
    UnloadTexture(textures->washed_potato);
    UnloadTexture(textures->sliced_potato);
    UnloadTexture(textures->peeled_potato);
    UnloadTexture(textures->fried_potato);
    UnloadTexture(textures->dirty_cucumber);
    UnloadTexture(textures->washed_cucumber);
    UnloadTexture(textures->sliced_cucumber);
    UnloadTexture(textures->dirty_tomato);
    UnloadTexture(textures->washed_tomato);
    UnloadTexture(textures->sliced_tomato);
    UnloadTexture(textures->salad);
    UnloadTexture(textures->guide_juice);
    UnloadTexture(textures->guide_potato);
    UnloadTexture(textures->guide_salad);
    UnloadTexture(textures->image1);
    UnloadTexture(textures->image2);
    UnloadTexture(textures->map1);
    UnloadTexture(textures->map2);
    UnloadTexture(textures->cloud);
    UnloadTexture(textures->f_button);
}
