#include "../inc/header.h"

void mx_load_textures(t_game_textures *textures) {
    textures->settings = LoadTexture("resource/images/settings.png");
    textures->volume_on = LoadTexture("resource/images/volume_high.png");
    textures->volume_on2 = LoadTexture("resource/images/volume_low.png");
    textures->music_on = LoadTexture("resource/images/music_on.png");
    textures->arrow = LoadTexture("resource/images/arrow_back.png");
    textures->volume_off = LoadTexture("resource/images/volume_off.png");
    textures->music_off = LoadTexture("resource/images/music_off.png");
    textures->del_texture = LoadTexture("resource/images/warning.png");
    textures->guide = LoadTexture("resource/images/guide_icon.png");
    textures->exit = LoadTexture("resource/images/exit.png");
    textures->pause = LoadTexture("resource/images/pause.png");
    textures->background = LoadTexture("resource/images/menu_background.png");
    textures->play_button = LoadTexture("resource/images/play_button.png");
    textures->star = LoadTexture("resource/images/star.png");
    textures->one_player = LoadTexture("resource/images/one_player.png");
    textures->two_players = LoadTexture("resource/images/two_players.png");
    textures->chef = LoadTexture("resource/images/chef.png");
    textures->right_arrow = LoadTexture("resource/images/arrow_right.png");
    textures->map3 = LoadTexture("resource/images/map_lvl_3.png");
    textures->image3 = LoadTexture("resource/images/preview_lvl_3.png");
    textures->level_preview = LoadTexture("resource/images/default_preview.png");
    textures->left_arrow = LoadTexture("resource/images/arrow_left.png");
    textures->served_icon = LoadTexture("resource/images/served_icon.png");
    textures->guest = LoadTexture("resource/images/bee.png");
    textures->reversed_guest = LoadTexture("resource/images/reversed_bee.png");
    textures->dirty_apple = LoadTexture("resource/images/dirty_apple.png");
    textures->washed_apple = LoadTexture("resource/images/washed_apple.png");
    textures->sliced_apple = LoadTexture("resource/images/sliced_apple.png");
    textures->juice = LoadTexture("resource/images/juice.png");
    textures->dirty_potato = LoadTexture("resource/images/dirty_potato.png");
    textures->washed_potato = LoadTexture("resource/images/washed_potato.png");
    textures->peeled_potato = LoadTexture("resource/images/peeled_potato.png");
    textures->sliced_potato = LoadTexture("resource/images/sliced_potato.png");
    textures->fried_potato = LoadTexture("resource/images/fried_potato.png");
    textures->dirty_cucumber = LoadTexture("resource/images/dirty_cucumber.png");
    textures->washed_cucumber = LoadTexture("resource/images/washed_cucumber.png");
    textures->sliced_cucumber = LoadTexture("resource/images/sliced_cucumber.png");
    textures->dirty_tomato = LoadTexture("resource/images/dirty_tomato.png");
    textures->washed_tomato = LoadTexture("resource/images/washed_tomato.png");
    textures->sliced_tomato = LoadTexture("resource/images/sliced_tomato.png");
    textures->salad = LoadTexture("resource/images/salad.png");
    textures->guide_juice = LoadTexture("resource/images/guide_juice.png");
    textures->guide_potato = LoadTexture("resource/images/guide_potato.png");
    textures->guide_salad = LoadTexture("resource/images/guide_salad.png");
    textures->image1 = LoadTexture("resource/images/preview_lvl_1.png");
    textures->image2 = LoadTexture("resource/images/preview_lvl_2.png");
    textures->map1 = LoadTexture("resource/images/map_lvl_1.png");
    textures->map2 = LoadTexture("resource/images/map_lvl_2.png");
    textures->cloud = LoadTexture("resource/images/cloud.png");
    textures->f_button = LoadTexture("resource/images/interaction_button.png");
    textures->controls = LoadTexture("resource/images/controls.png");
}

void mx_unload_textures(t_game_textures *textures) {
    UnloadTexture(textures->settings);
    UnloadTexture(textures->volume_on);
    UnloadTexture(textures->volume_on2);
    UnloadTexture(textures->music_on);
    UnloadTexture(textures->volume_off);
    UnloadTexture(textures->music_off);
    UnloadTexture(textures->arrow);
    UnloadTexture(textures->guide);
    UnloadTexture(textures->del_texture);
    UnloadTexture(textures->background);
    UnloadTexture(textures->play_button);
    UnloadTexture(textures->star);
    UnloadTexture(textures->exit);
    UnloadTexture(textures->pause);
    UnloadTexture(textures->one_player);
    UnloadTexture(textures->two_players);
    UnloadTexture(textures->chef);
    UnloadTexture(textures->right_arrow);
    UnloadTexture(textures->map3);
    UnloadTexture(textures->image3);
    UnloadTexture(textures->level_preview);
    UnloadTexture(textures->left_arrow);
    UnloadTexture(textures->served_icon);
    UnloadTexture(textures->guest);
    UnloadTexture(textures->reversed_guest);
    UnloadTexture(textures->dirty_apple);
    UnloadTexture(textures->washed_apple);
    UnloadTexture(textures->sliced_apple);
    UnloadTexture(textures->juice);
    UnloadTexture(textures->dirty_potato);
    UnloadTexture(textures->washed_potato);
    UnloadTexture(textures->sliced_potato);
    UnloadTexture(textures->peeled_potato);
    UnloadTexture(textures->fried_potato);
    UnloadTexture(textures->dirty_cucumber);
    UnloadTexture(textures->washed_cucumber);
    UnloadTexture(textures->sliced_cucumber);
    UnloadTexture(textures->dirty_tomato);
    UnloadTexture(textures->washed_tomato);
    UnloadTexture(textures->sliced_tomato);
    UnloadTexture(textures->salad);
    UnloadTexture(textures->guide_juice);
    UnloadTexture(textures->guide_potato);
    UnloadTexture(textures->guide_salad);
    UnloadTexture(textures->image1);
    UnloadTexture(textures->image2);
    UnloadTexture(textures->map1);
    UnloadTexture(textures->map2);
    UnloadTexture(textures->cloud);
    UnloadTexture(textures->f_button);
    UnloadTexture(textures->controls);
}
